USE [master]
GO

/****** Object:  Database [VIP Avto]    Script Date: 23.09.2024 9:08:50 ******/
CREATE DATABASE [VIP Avto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VIP Avto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\VIP Avto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VIP Avto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\VIP Avto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VIP Avto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VIP Avto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VIP Avto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VIP Avto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VIP Avto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VIP Avto] SET ARITHABORT OFF 
GO

ALTER DATABASE [VIP Avto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VIP Avto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VIP Avto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VIP Avto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VIP Avto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VIP Avto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VIP Avto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VIP Avto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VIP Avto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VIP Avto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VIP Avto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VIP Avto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VIP Avto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VIP Avto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VIP Avto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VIP Avto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VIP Avto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VIP Avto] SET RECOVERY FULL 
GO

ALTER DATABASE [VIP Avto] SET  MULTI_USER 
GO

ALTER DATABASE [VIP Avto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VIP Avto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VIP Avto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VIP Avto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VIP Avto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VIP Avto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [VIP Avto] SET QUERY_STORE = ON
GO

ALTER DATABASE [VIP Avto] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [VIP Avto] SET  READ_WRITE 
GO


